### ISSUE TITLE
Improve help/usage text

### ISSUE THREAD

**Issue by tukusejssirs** [nigelhorne/gedcal#101]
I really miss the `-h/--help` option. You have already implemented `-h` for different purpose, so at least `--help` should be implemented.

Also, I think that usage output should be a separate function (e.g. `usage()`). For now, it could accept one parameter, either `short` (short usage help text when the program dies) or `full` (full help text when issued with `--help` (then it should return `0` as it is a success).

The full help text should include all options with there definitions (just like it is currently in the [`README.md`](https://github.com/nigelhorne/gedcom/blob/master/README.md#reference).

The full help text should also include examples.

**Comment by nigelhorne** [comment]
Use '-?' to get help.  This is a convention going back many years as far back as the days of UNIX.
